pipeline:
  name: Harness Demo
  identifier: Harness_Demo
  projectIdentifier: DemoProject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: lalitbhadane
                    repoName: java-hello-world-with-maven
                    build:
                      type: branch
                      spec:
                        branch: master
          infrastructure:
            type: VM
            spec:
              type: Pool
              spec:
                poolName: ubuntu-ci-pool
                os: Linux
          caching:
            enabled: false
            paths: []
