pipeline:
  name: Java Basic Pipeline
  identifier: Java_Basic_Pipeline
  projectIdentifier: DemoProject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Build Java app
                  identifier: Build_Java_app
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      mvn -B package --file pom.xml
              - step:
                  type: Plugin
                  name: docker build
                  identifier: docker_build
                  spec:
                    connectorRef: HarnessDocker
                    image: plugins/docker
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          caching:
            enabled: false
            paths: []
